version: '3.6'

networks:
  inner-net:
    external: false
    name: inner-net

volumes:
    rabbitmq_data: {}
    postgres_auth: {}
    postgres_account: {}

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/bitnami
    networks:
      - inner-net
    # ports:
    #   - '5672:5672'
    #   - '15672:15672'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - inner-net
    command: redis-server --requirepass ${CACHE_SERVER_PASSWD}
    # ports:
    #   - 6379:6379
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    volumes:
      - /data/services/redis:/data
  auth-db:
    container_name: auth-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${AUTH_POSTGRES_DB:-mydb}
      PGDATA: /data/postgres
    volumes:
       - postgres_auth:/data/postgres
    # ports:
    #   - "5432:5432"
    networks:
      - inner-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
  # auth_db_admin:
  #   container_name: auth_db_admin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${AUTH_PGADMIN_DEFAULT_EMAIL:-example@abc.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${AUTH_PGADMIN_DEFAULT_PASSWORD:-TBcsdwuESD}
  #   volumes:
  #      - auth_pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - inner-net
  #   restart: unless-stopped
  account_db:
    container_name: account_db
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${ACCOUNT_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${ACCOUNT_POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${ACCOUNT_POSTGRES_DB:-mydb}
      PGDATA: /data/postgres
    volumes:
       - postgres_account:/data/postgres
    # ports:
    #   - "5432:5432"
    networks:
      - inner-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s