version: '3.6'

networks:
  inner-net:
    external: false
    name: inner-net

volumes:
    rabbitmq_data: {}
    postgres:

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/bitnami
    networks:
      - inner-net
    # ports:
    #   - '5672:5672'
    #   - '15672:15672'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - inner-net
    command: redis-server --requirepass ${CACHE_SERVER_PASSWD}
    # ports:
    #   - 6379:6379
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    volumes:
      - /data/services/redis:/data
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    networks:
      - inner-net
    volumes:
      - /data/services/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    env_file: .env
    # ports:
    #   - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    # ports:
    #   - "5432:5432"
    networks:
      - inner-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-example@abc.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-TBcsdwuESD}
  #   volumes:
  #      - pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - inner-net
  #   restart: unless-stopped